### ISSUE TITLE
Still seeing snakeoil issue

### ISSUE THREAD

**Issue by andystanton** [helmi03/docker-postgis#10]
Hi @helmi03, did you build and push to docker hub after merging? I still see

```
 * Starting PostgreSQL 9.3 database server
 * The PostgreSQL server failed to start. Please check the log output:
2014-09-14 20:33:46 UTC FATAL:  could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied
   ...fail!
2014/09/14 21:33:53 The command [/bin/sh -c service postgresql start && ./setup-docker.sh] returned a non-zero code: 1
```

when using `FROM    helmi03/docker-postgis` in a Dockerfile.

I deleted all local images to make sure it pulled the latest from Docker hub.

**Comment by helmi03** [comment]
snakeoil issue happen when using image from docker pull helmi03/docker-postgis.
What you could do is, rebuilding from scratch (tested docker 1.2), i.e. docker build

I think this is related to aufs specific issue, docker/docker/issues/783
See also:
- helmi03/docker-postgis/issues/4
- hw-cookbooks/postgresql/issues/156

I already trigger docker hub build many times, https://registry.hub.docker.com/u/helmi03/docker-postgis/builds_history/4435/
