### ISSUE TITLE
Docker Hub address changed

### ISSUE THREAD

**Issue by johnjohndoe** [helmi03/docker-postgis#11]
I noticed that the URL you are showing for the corresponding Docker Hub page is **not reachable** any longer. Please replace it.
- Not working: https://index.docker.io/u/helmi03/postgis/
- Suggested new URL: https://registry.hub.docker.com/u/helmi03/docker-postgis/

**Comment by helmi03** [comment]
thanks

Fixed: https://github.com/helmi03/docker-postgis/commit/0ae5ccd7253214d3f06b1cefad5266bc9799b53a

**Comment by johnjohndoe** [comment]
It is still wrong on the top of the page.
